// Code generated by simplefin-gen. DO NOT EDIT.
// Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
// Spec: https://www.simplefin.org/protocol.html

package simplefin

import "encoding/json"

// Canonical serialization exists so that every language target can be proved
// to parse the same fixture into the same result.
//
// The shape is deliberately not the wire format: keys are the SDK's camelCase
// names and every field is present, with absent values written as their zero
// ("" / 0 / false / null / []). Go marshals maps with keys sorted
// alphabetically, and the other language targets sort their keys to match, so
// two implementations that agree byte-for-byte here really did parse the
// fixture the same way.
//
// `extra` objects and the raw error payload are excluded: their contents are
// server-specific, so comparing them across languages would test the test
// harness rather than the parser.

func canonicalError(v Error) map[string]any {
	return map[string]any{
		"code":      string(v.Code),
		"msg":       v.Msg,
		"connId":    v.ConnID,
		"accountId": v.AccountID,
	}
}

func canonicalErrorSlice(in []Error) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalError(v))
	}
	return out
}

func canonicalConnection(v Connection) map[string]any {
	return map[string]any{
		"connId":  v.ConnID,
		"name":    v.Name,
		"orgId":   v.OrgID,
		"orgName": v.OrgName,
		"orgUrl":  v.OrgURL,
		"sfinUrl": v.SfinURL,
	}
}

func canonicalConnectionSlice(in []Connection) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalConnection(v))
	}
	return out
}

func canonicalTransaction(v Transaction) map[string]any {
	return map[string]any{
		"id":           v.ID,
		"posted":       v.Posted,
		"amount":       v.Amount,
		"description":  v.Description,
		"transactedAt": v.TransactedAt,
		"pending":      v.Pending,
	}
}

func canonicalTransactionSlice(in []Transaction) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalTransaction(v))
	}
	return out
}

func canonicalAccount(v Account) map[string]any {
	return map[string]any{
		"id":               v.ID,
		"name":             v.Name,
		"connId":           v.ConnID,
		"connName":         v.ConnName,
		"currency":         v.Currency,
		"balance":          v.Balance,
		"availableBalance": canonicalOptionalString(v.AvailableBalance),
		"balanceDate":      v.BalanceDate,
		"transactions":     canonicalTransactionSlice(v.Transactions),
	}
}

func canonicalAccountSlice(in []Account) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalAccount(v))
	}
	return out
}

func canonicalInfo(v Info) map[string]any {
	return map[string]any{
		"versions": canonicalStrings(v.Versions),
	}
}

func canonicalInfoSlice(in []Info) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalInfo(v))
	}
	return out
}

func canonicalCurrency(v Currency) map[string]any {
	return map[string]any{
		"name": v.Name,
		"abbr": v.Abbr,
	}
}

func canonicalCurrencySlice(in []Currency) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, v := range in {
		out = append(out, canonicalCurrency(v))
	}
	return out
}

// canonicalAccountSet renders the root response in canonical form.
func canonicalAccountSet(v *AccountSet) map[string]any {
	if v == nil {
		return map[string]any{}
	}
	return map[string]any{
		"errlist":     canonicalErrorSlice(v.Errlist),
		"connections": canonicalConnectionSlice(v.Connections),
		"accounts":    canonicalAccountSlice(v.Accounts),
	}
}

// CanonicalJSON renders an AccountSet in the canonical cross-language form.
// It is exported for use by the conformance tests and by anyone comparing two
// SDK implementations.
func CanonicalJSON(v *AccountSet) ([]byte, error) {
	return json.MarshalIndent(canonicalAccountSet(v), "", "  ")
}

func canonicalStrings(in []string) []string {
	if in == nil {
		return []string{}
	}
	return in
}

// canonicalOptionalString writes an absent optional as JSON null rather than
// an empty string, so "no available balance reported" stays distinguishable
// from "an available balance of nothing".
func canonicalOptionalString(in *string) any {
	if in == nil {
		return nil
	}
	return *in
}
