// Code generated by simplefin-gen. DO NOT EDIT.
// Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
// Spec: https://www.simplefin.org/protocol.html

package simplefin

import (
	"errors"
	"fmt"
)

// HTTPError is returned for any non-2xx status the protocol does not assign a
// specific meaning to.
//
// Op is always a fixed literal such as "GET /accounts" and never the request
// URL, because an Access URL embeds Basic Auth credentials and error strings
// end up in logs.
type HTTPError struct {
	// Status is the HTTP status code received.
	Status int
	// Op names the operation that failed, as a fixed literal.
	Op string
}

func (e *HTTPError) Error() string {
	return fmt.Sprintf("simplefin: %s failed with status %d", e.Op, e.Status)
}

// Sentinel errors for the statuses the protocol assigns meaning to. Compare
// with errors.Is.
var (
	// ErrPaymentRequired Payment required.
	ErrPaymentRequired = errors.New("simplefin: paymentrequired (402)")
	// ErrAuth Authentication failed. This could be because access has been
	// revoked or if the credentials are incorrect. When claiming, it means the
	// token either does not exist or has already been claimed by someone else
	// — which could mean the user's transaction information has been
	// compromised. SimpleFIN auth is all-or-nothing per Access URL, so this is
	// the signal to re-claim the whole Access URL rather than relink one
	// connection.
	ErrAuth = errors.New("simplefin: auth (403)")
)

// statusError maps an HTTP status to an error, or nil for success.
func statusError(status int, op string) error {
	switch {
	case status >= 200 && status < 300:
		return nil
	case status == 402:
		return fmt.Errorf("%w (%s)", ErrPaymentRequired, op)
	case status == 403:
		return fmt.Errorf("%w (%s)", ErrAuth, op)
	default:
		return &HTTPError{Status: status, Op: op}
	}
}
