// Code generated by simplefin-gen. DO NOT EDIT.
// Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
// Spec: https://www.simplefin.org/protocol.html

package simplefin

import "strings"

// ErrorCode identifies a SimpleFIN error.
//
// Codes are in the format prefix.[subcode]. This is a defined string type
// rather than a bare string so that editors offer the known codes on
// completion, while still accepting subcodes this SDK has not seen — the
// protocol requires consumers to tolerate unknown subcodes by falling back to
// the naked prefix. See Normalized.
type ErrorCode string

const (
	// ErrCodeAccount General account-level error.
	// Carries AccountID.
	ErrCodeAccount ErrorCode = "act."
	// ErrCodeAccountFailed Failed to get account information. Try again later.
	// Carries AccountID.
	ErrCodeAccountFailed ErrorCode = "act.failed"
	// ErrCodeAccountMissingData Incomplete transaction listing. Try again
	// later.
	// Carries AccountID.
	ErrCodeAccountMissingData ErrorCode = "act.missingdata"
	// ErrCodeConnection General connection-level error.
	// Carries ConnID.
	ErrCodeConnection ErrorCode = "con."
	// ErrCodeConnectionAuth Authentication issue for a connection.
	// Carries ConnID.
	ErrCodeConnectionAuth ErrorCode = "con.auth"
	// ErrCodeGeneral General error.
	ErrCodeGeneral ErrorCode = "gen."
	// ErrCodeGeneralAPI Error in how the API is being used. This is meant for
	// the developer and not the user.
	ErrCodeGeneralAPI ErrorCode = "gen.api"
	// ErrCodeGeneralAuth General authentication error (to the SimpleFIN
	// Server).
	ErrCodeGeneralAuth ErrorCode = "gen.auth"
)

// Error code prefixes.
const (
	// ErrPrefixAct marks account-level errors.
	ErrPrefixAct = "act"
	// ErrPrefixCon marks connection-level errors.
	ErrPrefixCon = "con"
	// ErrPrefixGen marks general-level errors.
	ErrPrefixGen = "gen"
)

// Prefix returns the code's prefix, so "con.auth" yields "con". An unknown
// code still yields a usable prefix.
func (c ErrorCode) Prefix() string {
	if i := strings.Index(string(c), "."); i >= 0 {
		return string(c)[:i]
	}
	return string(c)
}

// Known reports whether this is a code the specification defines.
func (c ErrorCode) Known() bool {
	switch c {
	case ErrCodeAccount:
		return true
	case ErrCodeAccountFailed:
		return true
	case ErrCodeAccountMissingData:
		return true
	case ErrCodeConnection:
		return true
	case ErrCodeConnectionAuth:
		return true
	case ErrCodeGeneral:
		return true
	case ErrCodeGeneralAPI:
		return true
	case ErrCodeGeneralAuth:
		return true
	}
	return false
}

// Normalized implements the protocol's fallback rule: consumers should handle
// unknown subcodes by treating them like the naked prefix. A known code is
// returned unchanged; an unrecognized one degrades to its prefix, so
// "con.somethingnew" becomes "con." and is still handled as a connection
// error rather than being dropped.
func (c ErrorCode) Normalized() ErrorCode {
	if c.Known() {
		return c
	}
	switch c.Prefix() {
	case "act":
		return "act."
	case "con":
		return "con."
	case "gen":
		return "gen."
	}
	return c
}

// IsAuth reports whether the code indicates an authentication problem, at
// either the server or the connection level.
func (c ErrorCode) IsAuth() bool {
	switch c.Normalized() {
	case ErrCodeGeneralAuth, ErrCodeConnectionAuth:
		return true
	}
	return false
}

// ProtocolVersion is a SimpleFIN protocol version accepted by GET /accounts.
type ProtocolVersion string

const (
	// ProtocolVersion1 selects protocol version 1.
	ProtocolVersion1 ProtocolVersion = "1"
	// ProtocolVersion2 selects protocol version 2.
	ProtocolVersion2 ProtocolVersion = "2"

	// DefaultProtocolVersion is sent when a caller does not choose one. The
	// specification lets the server pick when the parameter is absent, so this
	// SDK is explicit instead.
	DefaultProtocolVersion = ProtocolVersion2
)
