// Code generated by simplefin-gen. DO NOT EDIT.
// Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
// Spec: https://www.simplefin.org/protocol.html

package simplefin

import (
	"encoding/json"
	"time"
)

// Error A structured error from the Account Set's errlist. The protocol
// requires that these be displayed to the user, and that all strings be
// sanitized before display.
type Error struct {
	// Code One of the documented error codes.
	Code ErrorCode `json:"code"`
	// Msg String error suitable for displaying to users.
	Msg string `json:"msg"`
	// ConnID Connection id. This is only given if the error is specific to a
	// particular connection.
	ConnID string `json:"conn_id,omitempty"`
	// AccountID Account id. This is only given if the error is specific to a
	// particular account.
	AccountID string `json:"account_id,omitempty"`
	// Raw The error exactly as the server sent it. Preserved because the
	// protocol documents errlist as an array of objects without pinning their
	// shape, and because protocol v1 sent plain strings here.
	Raw any `json:"-"`
}

// Connection This represents a single connection to an institution. Users
// with 2 sets of login credentials for a particular bank will have 2
// different Connections, each with the same org_* fields.
type Connection struct {
	// ConnID ID of a particular connection for a financial institution.
	ConnID string `json:"conn_id"`
	// Name Human-friendly name for this connection. This should include the
	// financial institution name (and may be identical to the financial
	// institution's name in some cases).
	Name string `json:"name"`
	// OrgID ID of the financial institution. The ID must be unique per
	// SimpleFIN server, but it is not guaranteed to be globally unique.
	OrgID string `json:"org_id"`
	// OrgName Name of the financial institution. Present in the
	// specification's GET /accounts example but absent from its Connection
	// attribute table, so it is modelled as optional.
	OrgName string `json:"org_name,omitempty"`
	// OrgURL Domain name of the financial institution.
	OrgURL string `json:"org_url,omitempty"`
	// SfinURL Root URL of organization's SimpleFIN Server.
	SfinURL string `json:"sfin_url"`
}

// Transaction A single transaction within an Account.
type Transaction struct {
	// ID An ID that uniquely describes a transaction within an Account. An
	// organization may reuse transaction ids for different accounts, but may
	// never reuse a transaction id within an account.
	ID string `json:"id"`
	// Posted This is when the transaction posted to the account. If the
	// transaction is pending, this may be 0.
	// Unix epoch seconds. A value of zero or less means absent, not 1970.
	Posted int64 `json:"posted"`
	// Amount of transaction. Positive numbers indicate money being deposited
	// into the account.
	// This is a numeric string as sent by the server. Never parse it as a
	// float — SimpleFIN transmits amounts as strings precisely to avoid the
	// precision loss that causes.
	Amount string `json:"amount"`
	// Description A human-readable description of what the transaction was
	// for.
	Description string `json:"description"`
	// TransactedAt This is when the transaction happened.
	// Unix epoch seconds. A value of zero or less means absent, not 1970.
	TransactedAt int64 `json:"transacted_at,omitempty"`
	// Pending true indicates that this transaction has not yet posted. Default
	// is false (or absent), meaning the transaction has posted.
	Pending bool `json:"pending,omitempty"`
	// Extra This optional attribute may be used to include extra
	// transaction-specific data that is not defined in this standard. It is up
	// to the Server to decide whether or not to include data in here.
	Extra map[string]any `json:"extra,omitempty"`

	// Unknown holds wire keys this specification does not define, exactly as
	// the server sent them.
	//
	// SimpleFIN servers send fields the protocol never documented — the
	// Bridge attaches holdings to every account and payee, memo and mcc to
	// every transaction. Discarding them silently would lose real data, but
	// promoting them to typed fields would assert a shape the specification
	// does not guarantee. They are kept here instead, so nothing is lost and
	// nothing is invented. Use Field to read one with a type.
	Unknown map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes a Transaction, retaining any wire key this
// specification does not define in Unknown.
func (t *Transaction) UnmarshalJSON(data []byte) error {
	// The alias sheds this method, so the embedded decode does not recurse.
	type alias Transaction
	var base alias
	if err := json.Unmarshal(data, &base); err != nil {
		return err
	}
	*t = Transaction(base)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	for _, known := range []string{
		"amount",
		"description",
		"extra",
		"id",
		"pending",
		"posted",
		"transacted_at",
	} {
		delete(all, known)
	}
	if len(all) > 0 {
		t.Unknown = all
	}
	return nil
}

// PostedTime The transaction's effective date. posted is 0 while a
// transaction is pending, which would otherwise convert to 1970-01-01 and
// sort every pending row to the beginning of history. Falls back to
// transactedAt, then reports nothing.
func (t Transaction) PostedTime() *time.Time {
	if ts := epochToTime(t.Posted); ts != nil {
		return ts
	}
	return epochToTime(t.TransactedAt)
}

// TransactedTime transactedAt as a time, or null when unset.
func (t Transaction) TransactedTime() *time.Time {
	return epochToTime(t.TransactedAt)
}

// Account One account within a Connection. Note that `id` is unique only
// within its Connection, never globally — callers keying storage on `id`
// alone will collide across institutions.
type Account struct {
	// ID String that uniquely identifies the account within the Connection. It
	// is recommended that this id be chosen such that it does not reveal any
	// sensitive data (login information for the bank's web banking portal, for
	// instance).
	ID string `json:"id"`
	// Name A name that uniquely describes an account among all the users other
	// accounts. This name should be chosen so that a person can easily
	// associate it with only one of their accounts within an Connection.
	Name string `json:"name"`
	// ConnID ID of the account's Connection.
	ConnID string `json:"conn_id"`
	// ConnName Name of the account's Connection. Present in the
	// specification's GET /accounts example but absent from its Account
	// attribute table, so it is modelled as optional.
	ConnName string `json:"conn_name,omitempty"`
	// Currency If the currency is a standard currency, this is the currency
	// code from the official ISO 4217. For example "ZMW" or "USD". If this is
	// a custom currency, it is a URL — see resolveCurrency.
	Currency string `json:"currency"`
	// Balance The balance of the account as of balanceDate.
	// This is a numeric string as sent by the server. Never parse it as a
	// float — SimpleFIN transmits amounts as strings precisely to avoid the
	// precision loss that causes.
	Balance string `json:"balance"`
	// AvailableBalance The available balance of the account as of balanceDate.
	// This may be omitted if it is the same as balance.
	// This is a numeric string as sent by the server. Never parse it as a
	// float — SimpleFIN transmits amounts as strings precisely to avoid the
	// precision loss that causes.
	AvailableBalance *string `json:"available-balance,omitempty"`
	// BalanceDate The timestamp when the balance and available-balance became
	// what they are.
	// Unix epoch seconds. A value of zero or less means absent, not 1970.
	BalanceDate int64 `json:"balance-date"`
	// Transactions List of a subset of Transactions for this account, ordered
	// by posted.
	Transactions []Transaction `json:"transactions,omitempty"`
	// Extra This optional attribute may be used to include extra
	// account-specific data that is not defined in this standard. It is up to
	// the Server to decide whether or not to include data in here.
	Extra map[string]any `json:"extra,omitempty"`

	// Unknown holds wire keys this specification does not define, exactly as
	// the server sent them.
	//
	// SimpleFIN servers send fields the protocol never documented — the
	// Bridge attaches holdings to every account and payee, memo and mcc to
	// every transaction. Discarding them silently would lose real data, but
	// promoting them to typed fields would assert a shape the specification
	// does not guarantee. They are kept here instead, so nothing is lost and
	// nothing is invented. Use Field to read one with a type.
	Unknown map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes a Account, retaining any wire key this
// specification does not define in Unknown.
func (a *Account) UnmarshalJSON(data []byte) error {
	// The alias sheds this method, so the embedded decode does not recurse.
	type alias Account
	var base alias
	if err := json.Unmarshal(data, &base); err != nil {
		return err
	}
	*a = Account(base)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	for _, known := range []string{
		"available-balance",
		"balance",
		"balance-date",
		"conn_id",
		"conn_name",
		"currency",
		"extra",
		"id",
		"name",
		"org",
		"transactions",
	} {
		delete(all, known)
	}
	if len(all) > 0 {
		a.Unknown = all
	}
	return nil
}

// BalanceTime balanceDate as a time, or null when unset.
func (a Account) BalanceTime() *time.Time {
	return epochToTime(a.BalanceDate)
}

// AccountSet The GET /accounts response.
type AccountSet struct {
	// Errlist List of errors.
	Errlist []Error `json:"errlist"`
	// Connections List of Connections. In protocol v1 institution identity was
	// nested under each account as `org`; the normalizer synthesizes this
	// list.
	Connections []Connection `json:"connections"`
	// Accounts List of Accounts.
	Accounts []Account `json:"accounts"`
}

// Info The GET /info response, describing what the server supports.
type Info struct {
	// Versions An array of version string prefixes that this server supports.
	Versions []string `json:"versions"`
}

// Currency A custom currency, resolved by GET-ing an Account's currency
// URL. SimpleFIN supports custom currencies such as Frequent Flyer Miles,
// Rewards Points, and similar. All strings obtained from these requests
// must be sanitized when displaying them to users.
type Currency struct {
	// Name Human-readable name of the currency.
	Name string `json:"name"`
	// Abbr Human-readable short name of the currency.
	Abbr string `json:"abbr"`
}

// OrgV1 Protocol v1 nested institution identity inside each Account under
// `org`. Either domain or name is required; both may be specified.
// Protocol v2 replaced this with a top-level connections list.
type OrgV1 struct {
	// Domain name of the financial institution.
	Domain string `json:"domain,omitempty"`
	// Name of the financial institution.
	Name string `json:"name,omitempty"`
	// SfinURL Root URL of organization's SimpleFIN Server.
	SfinURL string `json:"sfin-url,omitempty"`
	// URL Optional URL of financial institution.
	URL string `json:"url,omitempty"`
	// ID Optional ID for the financial institution. The ID must be unique per
	// SimpleFIN server, but it is not guaranteed that IDs are globally unique.
	// Prefer domain as a globally unique ID for each institution.
	ID string `json:"id,omitempty"`
}

// Field reads a value out of an Unknown map and decodes it into T.
//
// It reports false when the key is absent or the value does not fit T, so an
// undocumented field that changes shape degrades to "not present" rather than
// failing the whole response.
//
//	holdings, ok := simplefin.Field[[]Holding](account.Unknown, "holdings")
//	payee, ok := simplefin.Field[string](tx.Unknown, "payee")
func Field[T any](unknown map[string]json.RawMessage, key string) (T, bool) {
	var out T
	raw, ok := unknown[key]
	if !ok {
		return out, false
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return out, false
	}
	return out, true
}

// epochToTime converts Unix seconds to a time, treating zero and negative
// values as absent. Every caller must agree on that rule — a bare zero check
// in one place and a > 0 check in another is how pending transactions end up
// dated to 1970 in one code path and null in the next.
func epochToTime(seconds int64) *time.Time {
	if seconds <= 0 {
		return nil
	}
	t := time.Unix(seconds, 0).UTC()
	return &t
}
