// Code generated by simplefin-gen. DO NOT EDIT.
// Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
// Spec: https://www.simplefin.org/protocol.html

package simplefin

import (
	"net/url"
	"strconv"
)

// GetAccountsParams are the documented query parameters for
// GET /accounts. The zero value requests protocol version
// 2 with no filters.
type GetAccountsParams struct {
	// StartDate If given, transactions will be restricted to those on or after
	// this Unix epoch timestamp.
	StartDate *int64
	// EndDate If given, transactions will be restricted to those before (but
	// not on) this Unix epoch timestamp.
	EndDate *int64
	// Pending If true, pending transactions will be included (if supported).
	// By default, pending transactions are NOT included.
	Pending bool
	// Accounts If given, only return information related to the given account
	// ids. Serialized as a repeated query parameter.
	Accounts []string
	// BalancesOnly If true, no transaction data is returned.
	BalancesOnly bool
	// Version Must be 2 for this version of the protocol. Can be 1 for earlier
	// versions. The server chooses the default version if this is not
	// specified; this SDK sends 2 unless told otherwise.
	Version ProtocolVersion
}

// Encode serializes the parameters into a query string.
//
// The serialization rules are not uniform and each one is load-bearing:
// boolean flags are opt-in and sent as "1" or omitted entirely (never "0"),
// account filters are a repeated key rather than a comma-joined list, and
// timestamps are raw Unix seconds.
func (p GetAccountsParams) Encode() url.Values {
	q := url.Values{}

	if p.StartDate != nil {
		q.Set("start-date", strconv.FormatInt(*p.StartDate, 10))
	}

	if p.EndDate != nil {
		q.Set("end-date", strconv.FormatInt(*p.EndDate, 10))
	}

	if p.Pending {
		q.Set("pending", "1")
	}

	for _, v := range p.Accounts {
		q.Add("account", v)
	}

	if p.BalancesOnly {
		q.Set("balances-only", "1")
	}

	version := p.Version
	if version == "" {
		version = DefaultProtocolVersion
	}
	q.Set("version", string(version))

	return q
}
