/**
 * Code generated by simplefin-gen. DO NOT EDIT.
 * Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
 * Spec: https://www.simplefin.org/protocol.html
 */

import type {
  SimpleFinError,
  Connection,
  Transaction,
  Account,
  AccountSet,
  Info,
  Currency,
} from "./models.js"

/*
 * Canonical serialization exists so that every language target can be proved
 * to parse the same fixture into the same result.
 *
 * The shape is deliberately not the wire format: keys are the SDK's camelCase
 * names and every field is present, with absent values written as their zero
 * ("" / 0 / false / null / []). Keys are sorted alphabetically to match Go's
 * map marshalling, so two implementations that agree byte-for-byte here
 * really did parse the fixture the same way.
 *
 * `extra` objects and the raw error payload are excluded: their contents are
 * server-specific, so comparing them across languages would test the test
 * harness rather than the parser.
 */

function canonicalError(v: SimpleFinError): Record<string, unknown> {
  return {
    "code": v.code ?? "",
    "msg": v.msg ?? "",
    "connId": v.connId ?? "",
    "accountId": v.accountId ?? "",
  }
}

function canonicalConnection(v: Connection): Record<string, unknown> {
  return {
    "connId": v.connId ?? "",
    "name": v.name ?? "",
    "orgId": v.orgId ?? "",
    "orgName": v.orgName ?? "",
    "orgUrl": v.orgUrl ?? "",
    "sfinUrl": v.sfinUrl ?? "",
  }
}

function canonicalTransaction(v: Transaction): Record<string, unknown> {
  return {
    "id": v.id ?? "",
    "posted": v.posted ?? 0,
    "amount": v.amount ?? "",
    "description": v.description ?? "",
    "transactedAt": v.transactedAt ?? 0,
    "pending": v.pending ?? false,
  }
}

function canonicalAccount(v: Account): Record<string, unknown> {
  return {
    "id": v.id ?? "",
    "name": v.name ?? "",
    "connId": v.connId ?? "",
    "connName": v.connName ?? "",
    "currency": v.currency ?? "",
    "balance": v.balance ?? "",
    "availableBalance": v.availableBalance ?? null,
    "balanceDate": v.balanceDate ?? 0,
    "transactions": (v.transactions ?? []).map(canonicalTransaction),
  }
}

function canonicalInfo(v: Info): Record<string, unknown> {
  return {
    "versions": v.versions ?? [],
  }
}

function canonicalCurrency(v: Currency): Record<string, unknown> {
  return {
    "name": v.name ?? "",
    "abbr": v.abbr ?? "",
  }
}

function canonicalAccountSet(v: AccountSet): Record<string, unknown> {
  return {
    "errlist": (v.errlist ?? []).map(canonicalError),
    "connections": (v.connections ?? []).map(canonicalConnection),
    "accounts": (v.accounts ?? []).map(canonicalAccount),
  }
}

/**
 * Renders an AccountSet in the canonical cross-language form.
 *
 * Exported for use by the conformance tests and by anyone comparing two SDK
 * implementations.
 */
export function canonicalJSON(v: AccountSet): string {
  return JSON.stringify(canonicalAccountSet(v), sortKeys, 2)
}


/**
 * A JSON.stringify replacer that emits object keys in alphabetical order,
 * matching how Go marshals a map. Without this the two languages would
 * produce the same data in a different order and the comparison would fail
 * for no real reason.
 */
function sortKeys(_key: string, value: unknown): unknown {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return value
  }
  const source = value as Record<string, unknown>
  const sorted: Record<string, unknown> = {}
  for (const k of Object.keys(source).sort()) {
    sorted[k] = source[k]
  }
  return sorted
}
