/**
 * Code generated by simplefin-gen. DO NOT EDIT.
 * Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
 * Spec: https://www.simplefin.org/protocol.html
 */

/**
 * Thrown for any non-2xx status the protocol does not assign a specific
 * meaning to.
 *
 * `op` is always a fixed literal such as `"GET /accounts"` and never the
 * request URL, because an Access URL embeds Basic Auth credentials and error
 * messages end up in logs.
 */
export class SimpleFinHttpError extends Error {
  override readonly name: string = "SimpleFinHttpError"
  /** The HTTP status code received. */
  readonly status: number
  /** The operation that failed, as a fixed literal. */
  readonly op: string

  constructor(status: number, op: string, message?: string) {
    super(message ?? `simplefin: ${op} failed with status ${status}`)
    this.status = status
    this.op = op
  }
}

/**
 * Payment required.
 */
export class SimpleFinPaymentRequiredError extends SimpleFinHttpError {
  override readonly name: string = "SimpleFinPaymentRequiredError"

  constructor(op: string) {
    super(402, op, `simplefin: paymentrequired (402) on ${op}`)
  }
}

/**
 * Authentication failed. This could be because access has been revoked or
 * if the credentials are incorrect. When claiming, it means the token
 * either does not exist or has already been claimed by someone else —
 * which could mean the user's transaction information has been
 * compromised. SimpleFIN auth is all-or-nothing per Access URL, so this is
 * the signal to re-claim the whole Access URL rather than relink one
 * connection.
 */
export class SimpleFinAuthError extends SimpleFinHttpError {
  override readonly name: string = "SimpleFinAuthError"

  constructor(op: string) {
    super(403, op, `simplefin: auth (403) on ${op}`)
  }
}

/**
 * Maps an HTTP status to an error, or null for success.
 */
export function statusError(status: number, op: string): SimpleFinHttpError | null {
  if (status >= 200 && status < 300) return null
  switch (status) {
    case 402:
      return new SimpleFinPaymentRequiredError(op)
    case 403:
      return new SimpleFinAuthError(op)
    default:
      return new SimpleFinHttpError(status, op)
  }
}

/*
 * Narrowing guards.
 *
 * TypeScript types a `catch` binding as `unknown`, so exporting error classes
 * alone would leave callers writing `as` casts to get at `status`. These
 * guards let a catch block narrow and autocomplete instead. They check the
 * `name` property rather than using `instanceof` so they still work when two
 * copies of the package end up in one dependency tree.
 */

/** Narrows an unknown caught value to any SimpleFIN HTTP error. */
export function isHttpError(e: unknown): e is SimpleFinHttpError {
  return (
    typeof e === "object" &&
    e !== null &&
    "op" in e &&
    "status" in e &&
    typeof (e as { status: unknown }).status === "number"
  )
}

/** Narrows an unknown caught value to a 402 error. */
export function isPaymentRequiredError(e: unknown): e is SimpleFinPaymentRequiredError {
  return isHttpError(e) && e.status === 402
}

/** Narrows an unknown caught value to a 403 error. */
export function isAuthError(e: unknown): e is SimpleFinAuthError {
  return isHttpError(e) && e.status === 403
}
