/**
 * Code generated by simplefin-gen. DO NOT EDIT.
 * Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
 * Spec: https://www.simplefin.org/protocol.html
 */

/**
 * Every error code the specification defines.
 *
 * Declared as a `const` object rather than a TypeScript `enum` so it is
 * tree-shakeable and survives `isolatedModules` / `erasableSyntaxOnly`.
 */
export const ErrorCodes = {
  /**
   * General account-level error.
   */
  Account: "act.",
  /**
   * Failed to get account information. Try again later.
   */
  AccountFailed: "act.failed",
  /**
   * Incomplete transaction listing. Try again later.
   */
  AccountMissingData: "act.missingdata",
  /**
   * General connection-level error.
   */
  Connection: "con.",
  /**
   * Authentication issue for a connection.
   */
  ConnectionAuth: "con.auth",
  /**
   * General error.
   */
  General: "gen.",
  /**
   * Error in how the API is being used. This is meant for the developer and
   * not the user.
   */
  GeneralAPI: "gen.api",
  /**
   * General authentication error (to the SimpleFIN Server).
   */
  GeneralAuth: "gen.auth",
} as const

/**
 * A SimpleFIN error code.
 *
 * The known codes are spelled out so editors offer them on completion, and
 * `(string & {})` keeps arbitrary strings assignable — the protocol requires
 * consumers to tolerate subcodes this SDK has never seen. See
 * {@link normalizeErrorCode}.
 */
export type ErrorCode = "act." | "act.failed" | "act.missingdata" | "con." | "con.auth" | "gen." | "gen.api" | "gen.auth" | (string & {})

/** An error code prefix: which layer the error belongs to. */
export type ErrorPrefix = "act" | "con" | "gen"

/**
 * Returns the code's prefix, so `"con.auth"` yields `"con"`. An unknown code
 * still yields a usable prefix.
 */
export function errorCodePrefix(code: ErrorCode): string {
  const i = code.indexOf(".")
  return i >= 0 ? code.slice(0, i) : code
}

const KNOWN_CODES = new Set<string>(Object.values(ErrorCodes))

/** Reports whether this is a code the specification defines. */
export function isKnownErrorCode(code: ErrorCode): boolean {
  return KNOWN_CODES.has(code)
}

/**
 * Implements the protocol's fallback rule: consumers should handle unknown
 * subcodes by treating them like the naked prefix. A known code is returned
 * unchanged; an unrecognized one degrades to its prefix, so
 * `"con.somethingnew"` becomes `"con."` and is still handled as a connection
 * error rather than dropped.
 */
export function normalizeErrorCode(code: ErrorCode): ErrorCode {
  if (isKnownErrorCode(code)) return code
  switch (errorCodePrefix(code)) {
    case "act":
      return "act."
    case "con":
      return "con."
    case "gen":
      return "gen."
    default:
      return code
  }
}

/**
 * Reports whether the code indicates an authentication problem, at either the
 * server or the connection level.
 */
export function isAuthErrorCode(code: ErrorCode): boolean {
  const normalized = normalizeErrorCode(code)
  return (
    normalized === ErrorCodes.GeneralAuth ||
    normalized === ErrorCodes.ConnectionAuth
  )
}

/** A SimpleFIN protocol version accepted by `GET /accounts`. */
export type ProtocolVersion = "1" | "2"

/**
 * Sent when a caller does not choose a version. The specification lets the
 * server pick when the parameter is absent, so this SDK is explicit instead.
 */
export const DEFAULT_PROTOCOL_VERSION: ProtocolVersion = "2"
