/**
 * Code generated by simplefin-gen. DO NOT EDIT.
 * Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
 * Spec: https://www.simplefin.org/protocol.html
 */

import type { ErrorCode } from "./errorcodes.js"

/**
 * A structured error from the Account Set's errlist. The protocol requires
 * that these be displayed to the user, and that all strings be sanitized
 * before display.
 */
export interface SimpleFinError {
  /**
   * One of the documented error codes.
   */
  code: ErrorCode
  /**
   * String error suitable for displaying to users.
   */
  msg: string
  /**
   * Connection id. This is only given if the error is specific to a
   * particular connection.
   */
  connId?: string
  /**
   * Account id. This is only given if the error is specific to a particular
   * account.
   */
  accountId?: string
  /**
   * The error exactly as the server sent it. Preserved because the protocol
   * documents errlist as an array of objects without pinning their shape,
   * and because protocol v1 sent plain strings here.
   */
  raw?: unknown
}

/**
 * This represents a single connection to an institution. Users with 2 sets
 * of login credentials for a particular bank will have 2 different
 * Connections, each with the same org_* fields.
 */
export interface Connection {
  /**
   * ID of a particular connection for a financial institution.
   */
  connId: string
  /**
   * Human-friendly name for this connection. This should include the
   * financial institution name (and may be identical to the financial
   * institution's name in some cases).
   */
  name: string
  /**
   * ID of the financial institution. The ID must be unique per SimpleFIN
   * server, but it is not guaranteed to be globally unique.
   */
  orgId: string
  /**
   * Name of the financial institution. Present in the specification's GET
   * /accounts example but absent from its Connection attribute table, so it
   * is modelled as optional.
   */
  orgName?: string
  /**
   * Domain name of the financial institution.
   */
  orgUrl?: string
  /**
   * Root URL of organization's SimpleFIN Server.
   */
  sfinUrl: string
}

/**
 * A single transaction within an Account.
 */
export interface Transaction {
  /**
   * An ID that uniquely describes a transaction within an Account. An
   * organization may reuse transaction ids for different accounts, but may
   * never reuse a transaction id within an account.
   */
  id: string
  /**
   * This is when the transaction posted to the account. If the transaction
   * is pending, this may be 0.
   *
   * @remarks
   * Unix epoch seconds. A value of zero or less means absent, not 1970.
   */
  posted: number
  /**
   * Amount of transaction. Positive numbers indicate money being deposited
   * into the account.
   *
   * @remarks
   * Numeric string as sent by the server. Never parse as a float —
   * SimpleFIN transmits amounts as strings precisely to avoid that precision
   * loss.
   */
  amount: string
  /**
   * A human-readable description of what the transaction was for.
   */
  description: string
  /**
   * This is when the transaction happened.
   *
   * @remarks
   * Unix epoch seconds. A value of zero or less means absent, not 1970.
   */
  transactedAt?: number
  /**
   * true indicates that this transaction has not yet posted. Default is
   * false (or absent), meaning the transaction has posted.
   */
  pending?: boolean
  /**
   * This optional attribute may be used to include extra
   * transaction-specific data that is not defined in this standard. It is up
   * to the Server to decide whether or not to include data in here.
   */
  extra?: Record<string, unknown>
}

/**
 * One account within a Connection. Note that `id` is unique only within
 * its Connection, never globally — callers keying storage on `id` alone
 * will collide across institutions.
 */
export interface Account {
  /**
   * String that uniquely identifies the account within the Connection. It is
   * recommended that this id be chosen such that it does not reveal any
   * sensitive data (login information for the bank's web banking portal, for
   * instance).
   */
  id: string
  /**
   * A name that uniquely describes an account among all the users other
   * accounts. This name should be chosen so that a person can easily
   * associate it with only one of their accounts within an Connection.
   */
  name: string
  /**
   * ID of the account's Connection.
   */
  connId: string
  /**
   * Name of the account's Connection. Present in the specification's GET
   * /accounts example but absent from its Account attribute table, so it is
   * modelled as optional.
   */
  connName?: string
  /**
   * If the currency is a standard currency, this is the currency code from
   * the official ISO 4217. For example "ZMW" or "USD". If this is a custom
   * currency, it is a URL — see resolveCurrency.
   */
  currency: string
  /**
   * The balance of the account as of balanceDate.
   *
   * @remarks
   * Numeric string as sent by the server. Never parse as a float —
   * SimpleFIN transmits amounts as strings precisely to avoid that precision
   * loss.
   */
  balance: string
  /**
   * The available balance of the account as of balanceDate. This may be
   * omitted if it is the same as balance.
   *
   * @remarks
   * Numeric string as sent by the server. Never parse as a float —
   * SimpleFIN transmits amounts as strings precisely to avoid that precision
   * loss.
   */
  availableBalance?: string
  /**
   * The timestamp when the balance and available-balance became what they
   * are.
   *
   * @remarks
   * Unix epoch seconds. A value of zero or less means absent, not 1970.
   */
  balanceDate: number
  /**
   * List of a subset of Transactions for this account, ordered by posted.
   */
  transactions?: Transaction[]
  /**
   * This optional attribute may be used to include extra account-specific
   * data that is not defined in this standard. It is up to the Server to
   * decide whether or not to include data in here.
   */
  extra?: Record<string, unknown>
}

/**
 * The GET /accounts response.
 */
export interface AccountSet {
  /**
   * List of errors.
   */
  errlist: SimpleFinError[]
  /**
   * List of Connections. In protocol v1 institution identity was nested
   * under each account as `org`; the normalizer synthesizes this list.
   */
  connections: Connection[]
  /**
   * List of Accounts.
   */
  accounts: Account[]
}

/**
 * The GET /info response, describing what the server supports.
 */
export interface Info {
  /**
   * An array of version string prefixes that this server supports.
   */
  versions: string[]
}

/**
 * A custom currency, resolved by GET-ing an Account's currency URL.
 * SimpleFIN supports custom currencies such as Frequent Flyer Miles,
 * Rewards Points, and similar. All strings obtained from these requests
 * must be sanitized when displaying them to users.
 */
export interface Currency {
  /**
   * Human-readable name of the currency.
   */
  name: string
  /**
   * Human-readable short name of the currency.
   */
  abbr: string
}

/**
 * Protocol v1 nested institution identity inside each Account under `org`.
 * Either domain or name is required; both may be specified. Protocol v2
 * replaced this with a top-level connections list.
 */
export interface OrgV1 {
  /**
   * Domain name of the financial institution.
   */
  domain?: string
  /**
   * Name of the financial institution.
   */
  name?: string
  /**
   * Root URL of organization's SimpleFIN Server.
   */
  sfinUrl?: string
  /**
   * Optional URL of financial institution.
   */
  url?: string
  /**
   * Optional ID for the financial institution. The ID must be unique per
   * SimpleFIN server, but it is not guaranteed that IDs are globally unique.
   * Prefer domain as a globally unique ID for each institution.
   */
  id?: string
}

/**
 * Converts Unix seconds to a Date, treating zero and negative values as
 * absent. Every caller must agree on that rule — a bare zero check in one
 * place and a > 0 check in another is how pending transactions end up dated
 * to 1970 in one code path and null in the next.
 */
export function epochToDate(seconds: number | undefined): Date | null {
  if (seconds === undefined || seconds <= 0) return null
  return new Date(seconds * 1000)
}

/**
 * The transaction's effective date. posted is 0 while a transaction is
 * pending, which would otherwise convert to 1970-01-01 and sort every
 * pending row to the beginning of history. Falls back to transactedAt,
 * then reports nothing.
 */
export function postedTime(t: Transaction): Date | null {
  const fromPosted = epochToDate(t.posted)
  if (fromPosted !== null) return fromPosted
  return epochToDate(t.transactedAt)
}

/**
 * transactedAt as a time, or null when unset.
 */
export function transactedTime(t: Transaction): Date | null {
  return epochToDate(t.transactedAt)
}

/**
 * balanceDate as a time, or null when unset.
 */
export function balanceTime(a: Account): Date | null {
  return epochToDate(a.balanceDate)
}
