/**
 * Code generated by simplefin-gen. DO NOT EDIT.
 * Source: spec/simplefin.yaml (SimpleFIN 2.0.0-draft)
 * Spec: https://www.simplefin.org/protocol.html
 */

import { DEFAULT_PROTOCOL_VERSION, type ProtocolVersion } from "./errorcodes.js"

/**
 * The documented query parameters for `GET /accounts`.
 *
 * Every property is optional; an empty object requests protocol version
 * 2 with no filters.
 */
export interface GetAccountsParams {
  /**
   * If given, transactions will be restricted to those on or after this Unix
   * epoch timestamp.
   *
   * @remarks
   * Accepts a `Date` or raw Unix epoch seconds.
   */
  startDate?: Date | number
  /**
   * If given, transactions will be restricted to those before (but not on)
   * this Unix epoch timestamp.
   *
   * @remarks
   * Accepts a `Date` or raw Unix epoch seconds.
   */
  endDate?: Date | number
  /**
   * If true, pending transactions will be included (if supported). By
   * default, pending transactions are NOT included.
   */
  pending?: boolean
  /**
   * If given, only return information related to the given account ids.
   * Serialized as a repeated query parameter.
   */
  accounts?: string[]
  /**
   * If true, no transaction data is returned.
   */
  balancesOnly?: boolean
  /**
   * Must be 2 for this version of the protocol. Can be 1 for earlier
   * versions. The server chooses the default version if this is not
   * specified; this SDK sends 2 unless told otherwise.
   */
  version?: ProtocolVersion
}

/** Converts a `Date` or raw epoch seconds into the Unix seconds the wire wants. */
function toUnixSeconds(value: Date | number): string {
  const seconds = value instanceof Date ? Math.floor(value.getTime() / 1000) : value
  return String(Math.trunc(seconds))
}

/**
 * Serializes the parameters into a query string.
 *
 * The serialization rules are not uniform and each one is load-bearing:
 * boolean flags are opt-in and sent as `"1"` or omitted entirely (never
 * `"0"`), account filters are a repeated key rather than a comma-joined list,
 * and timestamps are raw Unix seconds.
 */
export function encodeGetAccountsParams(
  params: GetAccountsParams = {},
): URLSearchParams {
  const q = new URLSearchParams()

  if (params.startDate !== undefined) {
    q.set("start-date", toUnixSeconds(params.startDate))
  }

  if (params.endDate !== undefined) {
    q.set("end-date", toUnixSeconds(params.endDate))
  }

  if (params.pending) {
    q.set("pending", "1")
  }

  for (const v of params.accounts ?? []) {
    q.append("account", v)
  }

  if (params.balancesOnly) {
    q.set("balances-only", "1")
  }

  const version: ProtocolVersion = params.version ?? DEFAULT_PROTOCOL_VERSION
  q.set("version", version)

  return q
}
